logging:
  level:
    ROOT: DEBUG
    com.github.kubenext: DEBUG
spring:
  profiles:
    active: dev
  devtools:
    restart:
      additional-exclude: .h2.server.properties
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/uaa?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      pool-name: Hikari
      auto-commit: false
  h2:
    console:
      enabled: false
  jpa:
    database-platform:
    database: h2
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: uaa
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
    hibernate:
      ddl-auto: update
#  liquibase:
#    contexts: dev
  mail:
    host: localhost
    port: 25
    username:
    password:
  messages:
    cache-duration: PT1S
  thymeleaf:
    cache: false

