spring:
  application:
    name: uaa
  profiles:
    active: dev
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: none
  messages:
    basename: i18n/messages
  thymeleaf:
    mode: HTML
info:
  display-profiles: dev
common:
  cache:
    hazelcast:
      instance-name: ${spring.application.name}
      default-package: com.github.kubenext.uaa.domain.*
  swagger:
    default-include-pattern: /api/.*
    title: UAA API
    description: Kubenext User Account and Authentication (UAA) Server
    version: 0.0.1
    terms-of-service-url: http://www.kubenext.com
    contact-name: Li.shangjin
    contact-url: http://www.kubenext.com
    contact-email: li.shangjin@icloud.com
    license: Apache License, Version 2.0
    license-url: http://www.apache.org/licenses/LICENSE-2.0

