spring:
  application:
    name: uaa
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://kubenext.auth0.com/
          jwk-set-uri: https://kubenext.auth0.com/.well-known/jwks.json