spring:
  application:
    name: uaa
  profiles:
    active: dev
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: none
  messages:
    basename: i18n/messages
  thymeleaf:
    mode: HTML
info:
  display-profiles: dev

